services:
    _defaults:
        autowire: true
        autoconfigure: true

    Mstudio\ContaoDashboard\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources}'

    Mstudio\ContaoDashboard\Controller\DashboardController:
        tags: ['controller.service_arguments']
        public: true
